#!/usr/bin/env bash
# shellcheck disable=SC2034

# Detection exit codes
DETECTION_SUCCESS=0
DETECTION_FAILURE=1
DETECTION_IGNORE=10
DETECTION_ALWAYS_INSTALL=11
DETECTION_NEVER_INSTALL=12
DETECTION_NOT_AVAILABLE=13
DETECTION_NO_LOGIC=20

# vim: syntax=sh cc=80 tw=79 ts=4 sw=4 sts=4 et sr
