# Detection exit codes
DETECTION_SUCCESS=0
DETECTION_FAILURE=1
DETECTION_ALWAYS_INSTALL=10
DETECTION_NEVER_INSTALL=11
DETECTION_NOT_AVAILABLE=12
DETECTION_NO_LOGIC=11

# vim: syntax=sh cc=80 tw=79 ts=4 sw=4 sts=4 et sr
