# pip
# https://pip.pypa.io/en/stable/
#
# File paths in preference order (Linux):
# - `${XDG_CONFIG_HOME:-$HOME/.config}/pip/pip.conf`
# - `$HOME/.pip/pip.conf`
#
# File paths in preference order (macOS):
# - `$XDG_DATA_HOME/pip/pip.conf`
#   Only if `$XDG_DATA_HOME` is non-empty.
# - `$HOME/Library/Application Support/pip/pip.conf`
#   Only if `$XDG_DATA_HOME` is unset or empty.
# - `$HOME/.config/pip/pip.conf`
# - `$HOME/.pip/pip.conf`
#
# File paths in preference order (Windows):
# - `%APPDATA%\pip\pip.ini`
# - `%HOME%\pip\pip.ini`

[list]
# Default output format
format = columns

# vim: syntax=dosini cc=80 tw=79 ts=4 sw=4 sts=4 et sr
